---
# bastion-assisted-installer tasks

- name: Create directories for bastion assisted-installer
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /opt/assisted-service
  - /opt/assisted-service/data

- name: Create directory for assisted-installer database
  file:
    path: /opt/assisted-service/data/postgresql
    state: directory
    owner: "26"
    recurse: true

- name: Download the rhcos image
  get_url:
    url: "{{ rhcos_image }}"
    dest: "/opt/assisted-service/{{ rhcos_image | basename }}"

- name: Get coreos-installer via podman
  containers.podman.podman_container:
    name: coreos-installer
    rm: true
    detach: false
    volume:
    - /opt/assisted-service:/data
    workdir: /data
    entrypoint: /bin/bash
    image: quay.io/coreos/coreos-installer:v0.7.0
    command: ["-c", "cp /usr/sbin/coreos-installer /data/coreos-installer"]
    state: started

- name: Template out assisted-installer files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - src: onprem-environment.j2
    dest: /opt/assisted-service/onprem-environment
  - src: nginx-ui.conf
    dest: /opt/assisted-service/nginx-ui.conf

- name: Create assisted-service pod
  containers.podman.podman_pod:
    name: assisted-service
    state: started
    ports:
    - 8000:8000
    - 8090:8090
    - 8888:8080

- name: Create database container in assisted-service pod
  containers.podman.podman_container:
    pod: assisted-service
    env_file: /opt/assisted-service/onprem-environment
    volume:
    - /opt/assisted-service/data/postgresql:/var/lib/pgsql
    name: db
    image: "{{ assisted_postgres_image }}"
    state: started

- name: Create assisted installer GUI container in assisted-service pod
  containers.podman.podman_container:
    pod: assisted-service
    env_file: /opt/assisted-service/onprem-environment
    volume:
    - /opt/assisted-service/nginx-ui.conf:/opt/bitnami/nginx/conf/server_blocks/nginx.conf
    name: gui
    image: "{{ assisted_service_gui_image }}"
    state: started

- name: Create assisted installer service container in assisted-service pod
  containers.podman.podman_container:
    pod: assisted-service
    env_file: /opt/assisted-service/onprem-environment
    volume:
    - "/opt/assisted-service/{{ rhcos_image | basename }}:/data/livecd.iso"
    - "/opt/assisted-service/coreos-installer:/data/coreos-installer"
    name: installer
    image: "{{ assisted_service_image }}"
    env:
      DUMMY_IGNITION: False
    state: started
